import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "3D Printer Filament",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className="relative min-h-screen bg-fixed bg-center bg-no-repeat overflow-auto xs:px-4" style={{ backgroundImage: "url('/bg.jpg')" }}>
        {/* Scrollable content */}
        <div className="relative z-10 w-full flex justify-center py-10">
          {children}
        </div>
      </body>
    </html>
  );
}
