import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "3D Printer Filament",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className="relative min-h-screen bg-fixed bg-center  bg-no-repeat overflow-auto px-4" style={{ backgroundImage: "url('/bg.jpg')" }}>
        
        {/* Optional dark overlay for readability */}
        <div className="fixed inset-0 bg-black/25 z-0"></div>

        {/* Decorative blobs */}
        <div className="fixed -top-10 -left-10 w-40 h-40 bg-green-200 rounded-full blur-3xl opacity-40 z-0" />
        <div className="fixed -bottom-10 -right-10 w-40 h-40 bg-blue-200 rounded-full blur-3xl opacity-40 z-0" />

        {/* Scrollable content */}
        <div className="relative z-10 w-full flex justify-center py-10">
          {children}
        </div>
      </body>
    </html>
  );
}
